version: '3.7'

services:
  peer-base:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dvpn_net
      # Logging configuration
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
      # TLS configuration
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer configuration
      - CORE_PEER_AUTHENTICATION_TIMEOUT=30s
      - CORE_PEER_EVENTS_TIMEOUT=30s
      # Gossip configuration
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=false
      # Enable operations service
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - CORE_METRICS_PROVIDER=prometheus
      # Enable mutual TLS
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      # Memory configuration
      - CORE_VM_DOCKER_HOSTCONFIG_MEMORY=536870912
      - CORE_CHAINCODE_EXECUTETIMEOUT=30s
      - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=30s
      - CORE_PEER_KEEPALIVE_DELIVERCLIENT_TIMEOUT=30s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/